---
# A workaround for maxhoesel.borgbackup.borgmatic that does not support custom paths
- name: "Create symbolic links for Borgmatic executables"
  loop:
    - borgmatic
    - generate-borgmatic-config
    - validate-borgmatic-config
  ansible.builtin.file:
    state: link
    src: "{{ borgmatic_pipx_bin_dir }}/{{ item }}"
    dest: /usr/bin/{{ item }}

- name: "Configure and run Borgmatic"
  ansible.builtin.include_role:
    name: maxhoesel.borgbackup.borgmatic
  vars:
    borgmatic_install: false  # we handle installation separately to get the recent version
    # borgmatic_ssh_key_gen_options: "-t ed25519 -a 100"
    borgmatic_ssh_key_path: "{{ ssh_key_path }}"
    borgmatic_schedule_on: "{{ borgmatic_schedule_oncalendar }}"
    borgmatic_schedule_max_random_delay: 600
    borgmatic_config:
      source_directories: "{{ borg_source_directories }}"
      repositories:
        - path: "{{ borg_repo_path }}"
          label: "{{ borg_repo_label }}"
      encryption_passphrase: "{{ borg_encryption_passphrase }}"
      # archive keeping configuration
      keep_hourly: 24
      keep_daily: 7
      keep_weekly: 4
      keep_monthly: 6
      compression: lz4
      # output configuration
      list_details: true
      statistics: true
      exclude_caches: true
      # logging verbosity:
      verbosity: 1
      syslog_verbosity: 1
      monitoring_verbosity: 1
      # consistency:
      checks:
        - name: repository
        - name: archives
      check_last: 3
      # used for compatibility with the Borgmatic-endorsed Loki dashboard
      before_backup:
        - echo "Starting a backup job."
      after_backup:
        - echo "Backup created."
      on_error:
        - echo "Error while creating a backup."
      # monitoring integrations
      # uptime_kuma:
      #   push_url: http://kuma.adm.local:3001/api/push/ZMi7Bd8kFV
      #   states:
      #     - finish
      # loki:
      #   url: http://loki.adm.local:3100/loki/api/v1/push
      #   labels:
      #     instance: borgmatic
      #     app: borgmatic
      #     hostname: __hostname
